### PR TITLE
Support for handling sources.list in ubuntu and debian - reprise

### PR DESCRIPTION
**Pull request by gionn**
This is a rework of the original PR #102 

Now the used attributes are similar to the [ubuntu cookbook attributes](https://github.com/opscode-cookbooks/ubuntu/blob/master/attributes/default.rb), actually deprecating it.

I've also added README and a minitest (no excuses for not getting it merged now :love_letter: ).

### CODE REVIEW

**Comment by DennisBP** [comment]
:+1:

**Comment by gionn** [comment]
@someara @thommay is there anything blocking this merge?

**Comment by thommay** [comment]
@gionn thanks for the PR. we're currently discussing how the apt cookbook should look long term, and once we've done that, we'll figure out the most appropriate place to take this.

**Comment by gionn** [comment]
hey @thommay, every time I spin up a new vagrant instance in test-kitchen with the default us mirrors in sources.list, I remember about this PR.

Something is changed in the meantime?

**Comment by gionn** [comment]
:sob: no love for this? :sob:

**Comment by tas50** [comment]
We'd really like to avoid adding particular repositories to this cookbook.  We currently have the Ubuntu cookbook that manages the Ubuntu repositories.  If you're looking for that functionality you'll probably want to use that cookbook.

**Pull request closed without merging**
