### PR TITLE
Remove nil defaults in the repository provider

### PR DESCRIPTION
**Pull request by tas50**

### CODE REVIEW

**Comment by thommay** [comment]
why?

**Comment by iennae** [comment]
I think because it's of type String. We probably want to make it of type [String, nil] rather than eliminate them,  (for example, 'property :cookbook, [ String, nil ], default: nil'

**Comment by tas50** [comment]
@thom isn't our desired pattern to leave properties undefined vs. setting a default of nil?

**Comment by tas50** [comment]
@thommay any reason not to merge this?

**Pull request closed without merging**
